---
subject:
  C:  NL
  ST: Somestate
  L:  Somecity
  O:  Mannem Solutions
  OU: Chainsmith TLS chain maker
  CN: chainsmith

#tmpdir: /tmp/certs/postgres

intermediates:
  - name: server
    servers: {}
# You can set servers directly
#      host.example.com:
#        - 10.11.12.13
# And you can read servers from an ansible hostsfile (yaml formattted)
    environment: environments/poc/hosts
  - name: client
    clients:
      - postgres
      - wal-g
      - application
